# Generated by Django 3.2.3 on 2021-10-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='e_signup_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter firstname', models.CharField(max_length=100)),
                ('Enter lastname', models.CharField(max_length=100)),
                ('Enter email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='e_login_model',
        ),
    ]
