# Generated by Django 3.2.3 on 2021-10-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_emails', '0002_auto_20211022_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e_signup_model',
            old_name='Enter email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='e_signup_model',
            old_name='Enter firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='e_signup_model',
            old_name='Enter lastname',
            new_name='lastname',
        ),
    ]
