# Generated by Django 3.2.3 on 2021-10-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_emails', '0003_auto_20211022_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='e_login_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
