# Generated by Django 3.2.3 on 2021-10-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_emails', '0004_e_login_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='send_multi_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_address', models.CharField(max_length=100)),
                ('sender_password', models.CharField(max_length=100)),
                ('list_of_send_address', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='e_login_model',
        ),
        migrations.DeleteModel(
            name='e_signup_model',
        ),
    ]
