# Generated by Django 3.2.3 on 2021-10-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_emails', '0005_auto_20211024_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send_multi_email',
            name='list_of_send_address',
        ),
        migrations.RemoveField(
            model_name='send_multi_email',
            name='send_address',
        ),
        migrations.RemoveField(
            model_name='send_multi_email',
            name='sender_password',
        ),
        migrations.AddField(
            model_name='send_multi_email',
            name='add_recipient',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='send_multi_email',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='send_multi_email',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
