# Generated by Django 3.2.3 on 2021-10-24 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_emails', '0006_auto_20211024_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='send_multi_email',
            old_name='add_recipient',
            new_name='recipient',
        ),
    ]
